#!/usr/bin/env node
/* eslint-disable no-console */
/**
 * Seed the foods_staples table. Curated common foods that always
 * surface at the top of the food search panel.
 *
 *   node scripts/seed-staples.js
 *
 * Idempotent: uses upsert on the id PK. Re-running updates the
 * row in place.
 */

const SUPABASE_URL = process.env.SUPABASE_URL;
const KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !KEY) {
  console.error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY');
  process.exit(1);
}

// Common foods, region-scoped. Each row has kcal/protein/carbs/
// fat/fiber per 100g (or per 100ml for beverages).
const STAPLES = [
  // -------- PROTEINS --------
  { id: 'st-chicken-breast-raw', name: 'Chicken breast, raw', category: 'Meat & Poultry',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 120, protein: 22.5, carbs: 0, fat: 2.6, fiber: 0, serving_basis: '100g' },
  { id: 'st-chicken-thigh-skinless-raw', name: 'Chicken thigh, skinless, raw', category: 'Meat & Poultry',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 119, protein: 19.7, carbs: 0, fat: 3.7, fiber: 0, serving_basis: '100g' },
  { id: 'st-ground-beef-raw', name: 'Ground beef, 10% fat, raw', category: 'Meat & Poultry',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 176, protein: 20, carbs: 0, fat: 10, fiber: 0, serving_basis: '100g',
    aliases: [
      'mince',
      'minced beef',
      'chicken',
      'chicken breast',
      'grilled chicken',
      'poached chicken',
      'roast chicken',
      'chicken thigh',
      'grilled chicken thigh',
      'roast chicken thigh',
      'beef mince',
      'lean beef',
      '5% fat beef',
    ] },
  { id: 'st-pork-loin-raw', name: 'Pork loin, raw', category: 'Meat & Poultry',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 198, protein: 21.4, carbs: 0, fat: 12, fiber: 0, serving_basis: '100g' },
  { id: 'st-bacon-raw', name: 'Bacon, raw', category: 'Meat & Poultry',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 417, protein: 13, carbs: 1.4, fat: 39, fiber: 0, serving_basis: '100g',
    aliases: [
      'streaky bacon',
      'back bacon',
      'pork',
      'roast pork',
      'pork chop',
      'bacon rashers',
      'rashers',
    ] },
  { id: 'st-salmon-raw', name: 'Salmon, raw', category: 'Fish & Seafood',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 208, protein: 20, carbs: 0, fat: 13, fiber: 0, serving_basis: '100g' },
  { id: 'st-tuna-canned', name: 'Tuna, canned in water', category: 'Fish & Seafood',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 116, protein: 26, carbs: 0, fat: 1, fiber: 0, serving_basis: '100g' },
  { id: 'st-cod-raw', name: 'Cod, raw', category: 'Fish & Seafood',
    regions: ['uk-ie', 'us', 'europe', 'worldwide'],
    kcal: 82, protein: 18, carbs: 0, fat: 0.7, fiber: 0, serving_basis: '100g',
    aliases: [
      'cod fillet',
      'salmon fillet',
      'fresh salmon',
      'grilled salmon',
      'tinned tuna',
      'canned tuna',
      'tuna chunks',
      'tuna flakes',
      'tuna in brine',
      'cod loin',
      'fresh cod',
    ] },
  { id: 'st-haddock-raw', name: 'Haddock, raw', category: 'Fish & Seafood',
    regions: ['uk-ie', 'europe', 'worldwide'],
    kcal: 74, protein: 17, carbs: 0, fat: 0.7, fiber: 0, serving_basis: '100g' },
  { id: 'st-sea-bass-raw', name: 'Sea bass, raw', category: 'Fish & Seafood',
    regions: ['uk-ie', 'europe', 'worldwide'],
    kcal: 97, protein: 18, carbs: 0, fat: 2, fiber: 0, serving_basis: '100g',
    aliases: [
      'seabass',
      'sea bass fillet',
      'smoked haddock',
      'haddock fillet',
    ] },
  { id: 'st-sardines-canned', name: 'Sardines, canned in oil', category: 'Fish & Seafood',
    regions: ['uk-ie', 'europe', 'worldwide'],
    kcal: 208, protein: 24, carbs: 0, fat: 11, fiber: 0, serving_basis: '100g',
    aliases: [
      'sardines',
      'tinned sardines',
      'sardines in oil',
      'pilchards',
    ] },
  { id: 'st-sardines-canned-tomato', name: 'Sardines, canned in tomato sauce', category: 'Fish & Seafood',
    regions: ['uk-ie', 'europe', 'worldwide'],
    kcal: 180, protein: 20, carbs: 4, fat: 9, fiber: 0, serving_basis: '100g' },
  { id: 'st-mackerel-raw', name: 'Mackerel, raw', category: 'Fish & Seafood',
    regions: ['uk-ie', 'europe', 'worldwide'],
    kcal: 205, protein: 19, carbs: 0, fat: 14, fiber: 0, serving_basis: '100g' },
  { id: 'st-anchovies-canned', name: 'Anchovies, canned in oil', category: 'Fish & Seafood',
    regions: ['uk-ie', 'europe', 'worldwide'],
    kcal: 210, protein: 28, carbs: 0, fat: 10, fiber: 0, serving_basis: '100g',
    aliases: ['anchovies'] },
  { id: 'st-squid-raw', name: 'Squid, raw', category: 'Fish & Seafood',
    regions: ['uk-ie', 'europe', 'worldwide'],
    kcal: 76, protein: 16, carbs: 3, fat: 1, fiber: 0, serving_basis: '100g',
    aliases: ['squid', 'calamari'] },
  { id: 'st-squid-grilled', name: 'Squid, grilled', category: 'Fish & Seafood',
    regions: ['uk-ie', 'europe', 'worldwide'],
    kcal: 95, protein: 16, carbs: 3.5, fat: 1.5, fiber: 0, serving_basis: '100g' },
  { id: 'st-squid-rings-fried', name: 'Squid rings, fried', category: 'Fish & Seafood',
    regions: ['uk-ie', 'europe', 'worldwide'],
    kcal: 175, protein: 17, carbs: 8, fat: 8, fiber: 0, serving_basis: '100g',
    aliases: ['calamari', 'fried calamari', 'fried squid'] },
  { id: 'st-octopus-raw', name: 'Octopus, raw', category: 'Fish & Seafood',
    regions: ['europe', 'worldwide'],
    kcal: 82, protein: 15, carbs: 2, fat: 1, fiber: 0, serving_basis: '100g' },
  { id: 'st-prawns-raw', name: 'Prawns, raw', category: 'Fish & Seafood',
    regions: ['uk-ie', 'us', 'europe', 'worldwide'],
    kcal: 99, protein: 24, carbs: 0.2, fat: 0.3, fiber: 0, serving_basis: '100g',
    aliases: [
      'prawns',
      'shrimp',
      'king prawns',
      'raw prawns',
      'shell-on prawns',
    ] },
  { id: 'st-prawns-cooked', name: 'Prawns, cooked', category: 'Fish & Seafood',
    regions: ['uk-ie', 'us', 'europe', 'worldwide'],
    kcal: 99, protein: 24, carbs: 0.2, fat: 0.3, fiber: 0, serving_basis: '100g' },
  { id: 'st-mussels-cooked', name: 'Mussels, cooked', category: 'Fish & Seafood',
    regions: ['uk-ie', 'europe', 'worldwide'],
    kcal: 172, protein: 24, carbs: 7, fat: 5, fiber: 0, serving_basis: '100g',
    aliases: [
      'mussels',
      'prawns',
      'shrimp',
      'king prawns',
      'cooked prawns',
      'peeled prawns',
      'cooked mussels',
      'mussels in white wine',
      'moules mariniere',
    ] },
  { id: 'st-clams-cooked', name: 'Clams, cooked', category: 'Fish & Seafood',
    regions: ['uk-ie', 'us', 'europe', 'worldwide'],
    kcal: 148, protein: 26, carbs: 5, fat: 2, fiber: 0, serving_basis: '100g',
    aliases: [
      'clams',
      'cooked clams',
      'steamed clams',
    ] },
  { id: 'st-scallops-cooked', name: 'Scallops, cooked', category: 'Fish & Seafood',
    regions: ['uk-ie', 'us', 'europe', 'worldwide'],
    kcal: 111, protein: 23, carbs: 5, fat: 0.8, fiber: 0, serving_basis: '100g',
    aliases: [
      'scallops',
      'cooked scallops',
      'seared scallops',
    ] },
  { id: 'st-crab-cooked', name: 'Crab meat, cooked', category: 'Fish & Seafood',
    regions: ['uk-ie', 'us', 'europe', 'worldwide'],
    kcal: 97, protein: 19, carbs: 0, fat: 1.5, fiber: 0, serving_basis: '100g',
    aliases: [
      'crab',
      'crab meat',
      'white crab meat',
      'brown crab meat',
    ] },
  { id: 'st-lobster-cooked', name: 'Lobster, cooked', category: 'Fish & Seafood',
    regions: ['uk-ie', 'us', 'europe', 'worldwide'],
    kcal: 89, protein: 19, carbs: 0, fat: 0.5, fiber: 0, serving_basis: '100g' },
  { id: 'st-oysters-raw', name: 'Oysters, raw', category: 'Fish & Seafood',
    regions: ['uk-ie', 'us', 'europe', 'worldwide'],
    kcal: 51, protein: 5, carbs: 2, fat: 1.7, fiber: 0, serving_basis: '100g' },
  { id: 'st-tinned-salmon', name: 'Salmon, canned', category: 'Fish & Seafood',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 167, protein: 20, carbs: 0, fat: 9, fiber: 0, serving_basis: '100g' },
  { id: 'st-eggs-whole', name: 'Egg, whole, raw', category: 'Eggs',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 155, protein: 13, carbs: 1.1, fat: 11, fiber: 0, serving_basis: '100g' },
  { id: 'st-tofu-firm', name: 'Tofu, firm', category: 'Protein Foods',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 144, protein: 17, carbs: 3, fat: 9, fiber: 2, serving_basis: '100g' },
  { id: 'st-greek-yogurt', name: 'Greek yogurt, 0% fat', category: 'Dairy',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 59, protein: 10, carbs: 3.6, fat: 0.4, fiber: 0, serving_basis: '100g',
    aliases: [
      'greek yoghurt',
      'eggs',
      'boiled egg',
      'fried egg',
      'scrambled eggs',
      'omelette',
      'scrambled egg',
      'poached egg',
      'egg white',
      'egg yolk',
      'whole egg',
      'firm tofu',
      'soybean curd',
      'bean curd',
      'bean curd cake',
      'greek style yogurt',
      'thick yogurt',
      'strained yogurt',
      'lobster',
      'cooked lobster',
      'boiled lobster',
      'oysters',
      'raw oysters',
      'fresh oysters',
      'rock oysters',
      'native oysters',
      'tinned salmon',
      'canned salmon',
      'pink salmon',
    ] },
  { id: 'st-cottage-cheese', name: 'Cottage cheese', category: 'Dairy',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 98, protein: 11, carbs: 3.4, fat: 4.3, fiber: 0, serving_basis: '100g' },

  // -------- CARBS --------
  { id: 'st-white-rice-cooked', name: 'White rice, cooked', category: 'Grains',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 130, protein: 2.7, carbs: 28, fat: 0.3, fiber: 0.4, serving_basis: '100g' },
  { id: 'st-brown-rice-cooked', name: 'Brown rice, cooked', category: 'Grains',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 123, protein: 2.7, carbs: 25.6, fat: 1, fiber: 1.6, serving_basis: '100g' },
  { id: 'st-oats-rolled-cooked', name: 'Oats, rolled, cooked', category: 'Grains',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 71, protein: 2.5, carbs: 12, fat: 1.5, fiber: 1.7, serving_basis: '100g',
    aliases: [
      'oatmeal',
      'porridge oats',
      'cottage cheese',
      'curd cheese',
      'rice',
      'cooked rice',
      'boiled rice',
      'steamed rice',
      'jasmine rice',
      'basmati rice',
      'long grain rice',
      'wholegrain rice',
      'brown basmati',
      'long grain brown rice',
      'porridge',
      'oat bran',
      'rolled oats',
      'oats',
    ] },
  { id: 'st-pasta-cooked', name: 'Pasta, cooked', category: 'Pasta & Noodles',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 158, protein: 5.8, carbs: 30.9, fat: 0.9, fiber: 1.8, serving_basis: '100g' },
  { id: 'st-bread-white', name: 'White bread, sliced', category: 'Bread & Bakery',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 265, protein: 9, carbs: 49, fat: 3.2, fiber: 2.7, serving_basis: '100g' },
  { id: 'st-bread-wholemeal', name: 'Wholemeal bread, sliced', category: 'Bread & Bakery',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 247, protein: 13, carbs: 41, fat: 3.4, fiber: 7, serving_basis: '100g',
    aliases: [
      'whole wheat bread',
      'brown bread',
      'spaghetti',
      'penne',
      'fusilli',
      'macaroni',
      'tagliatelle',
      'pasta',
      'noodles',
      'rigatoni',
      'toast',
      'sliced bread',
      'bread',
      'sandwich bread',
      'white toast',
      'warburtons',
      'hovis',
      'wholemeal toast',
      'wholewheat bread',
    ] },
  { id: 'st-sweet-potato-cooked', name: 'Sweet potato, cooked', category: 'Vegetables',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 90, protein: 2, carbs: 20.7, fat: 0.2, fiber: 3.3, serving_basis: '100g' },
  { id: 'st-potato-cooked', name: 'Potato, boiled', category: 'Vegetables',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 87, protein: 1.9, carbs: 20.1, fat: 0.1, fiber: 1.8, serving_basis: '100g' },
  { id: 'st-quinoa-cooked', name: 'Quinoa, cooked', category: 'Grains',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 120, protein: 4.4, carbs: 21.3, fat: 1.9, fiber: 2.8, serving_basis: '100g' },
  { id: 'st-couscous-cooked', name: 'Couscous, cooked', category: 'Pasta & Noodles',
    regions: ['uk-ie', 'europe', 'worldwide'],
    kcal: 112, protein: 3.8, carbs: 23.2, fat: 0.2, fiber: 1.4, serving_basis: '100g' },

  // -------- FATS --------
  { id: 'st-olive-oil', name: 'Olive oil, extra virgin', category: 'Oils & Fats',
    regions: ['uk-ie', 'us', 'europe', 'worldwide'],
    kcal: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, serving_basis: '100ml' },
  { id: 'st-butter', name: 'Butter, salted', category: 'Oils & Fats',
    regions: ['uk-ie', 'us', 'europe', 'worldwide'],
    kcal: 717, protein: 0.9, carbs: 0.1, fat: 81, fiber: 0, serving_basis: '100g' },
  { id: 'st-avocado', name: 'Avocado', category: 'Fruits',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 160, protein: 2, carbs: 8.5, fat: 14.7, fiber: 6.7, serving_basis: '100g' },
  { id: 'st-almonds', name: 'Almonds, raw', category: 'Nuts & Seeds',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 579, protein: 21, carbs: 21.6, fat: 49.9, fiber: 12.5, serving_basis: '100g' },
  { id: 'st-peanut-butter', name: 'Peanut butter, smooth', category: 'Nuts & Seeds',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 588, protein: 25, carbs: 20, fat: 50, fiber: 6, serving_basis: '100g' },
  { id: 'st-cheddar', name: 'Cheddar cheese', category: 'Dairy',
    regions: ['uk-ie', 'us', 'europe', 'worldwide'],
    kcal: 403, protein: 25, carbs: 1.3, fat: 33, fiber: 0, serving_basis: '100g' },
  { id: 'st-mozzarella', name: 'Mozzarella', category: 'Dairy',
    regions: ['uk-ie', 'us', 'europe', 'worldwide'],
    kcal: 280, protein: 28, carbs: 3.1, fat: 17, fiber: 0, serving_basis: '100g' },
  { id: 'st-feta', name: 'Feta cheese', category: 'Dairy',
    regions: ['europe', 'worldwide'],
    kcal: 264, protein: 14, carbs: 4, fat: 21, fiber: 0, serving_basis: '100g' },

  // -------- VEG --------
  { id: 'st-broccoli', name: 'Broccoli, raw', category: 'Vegetables',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 34, protein: 2.8, carbs: 6.6, fat: 0.4, fiber: 2.6, serving_basis: '100g' },
  { id: 'st-spinach', name: 'Spinach, raw', category: 'Vegetables',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 23, protein: 2.9, carbs: 3.6, fat: 0.4, fiber: 2.2, serving_basis: '100g' },
  { id: 'st-tomato', name: 'Tomato, raw', category: 'Vegetables',
    regions: ['uk-ie', 'us', 'europe', 'worldwide'],
    kcal: 18, protein: 0.9, carbs: 3.9, fat: 0.2, fiber: 1.2, serving_basis: '100g' },
  { id: 'st-onion', name: 'Onion, raw', category: 'Vegetables',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 40, protein: 1.1, carbs: 9.3, fat: 0.1, fiber: 1.7, serving_basis: '100g' },
  { id: 'st-carrot', name: 'Carrot, raw', category: 'Vegetables',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 41, protein: 0.9, carbs: 9.6, fat: 0.2, fiber: 2.8, serving_basis: '100g' },
  { id: 'st-bell-pepper', name: 'Bell pepper, raw', category: 'Vegetables',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 31, protein: 1, carbs: 6, fat: 0.3, fiber: 2.1, serving_basis: '100g',
    aliases: [
      'capsicum',
      'sweet pepper',
      'sweet potato',
      'kumara',
      'yam',
      'potato',
      'boiled potato',
      'baked potato',
      'mashed potato',
      'jacket potato',
      'new potato',
      'quinoa',
      'red quinoa',
      'white quinoa',
      'couscous',
      'wholewheat couscous',
      'evoo',
      'extra virgin olive oil',
      'olive oil',
      'virgin olive oil',
      'cold pressed olive oil',
      'salted butter',
      'unsalted butter',
      'butter',
      'avocado pear',
      'haas avocado',
      'guacamole',
      'almond',
      'flaked almonds',
      'ground almonds',
      'whole almonds',
      'peanut spread',
      'smooth peanut butter',
      'crunchy peanut butter',
      'pb',
      'mature cheddar',
      'sharp cheddar',
      'mild cheddar',
      'cheese',
      'red leicester',
      'double gloucester',
      'mozzarella cheese',
      'fresh mozzarella',
      'buffalo mozzarella',
      'pizza mozzarella',
      'feta',
      'greek cheese',
      'salad cheese',
      'crumbled feta',
      'broccoli florets',
      'steamed broccoli',
      'purple sprouting broccoli',
      'tenderstem broccoli',
      'baby spinach',
      'baby leaf',
      'english spinach',
      'baby spinach leaves',
      'fresh tomato',
      'vine tomato',
      'beef tomato',
      'plum tomato',
      'roma tomato',
      'brown onion',
      'red onion',
      'white onion',
      'spanish onion',
      'yellow onion',
      'spring onion',
      'shallot',
      'carrots',
      'baby carrots',
      'rainbow carrots',
      'chantenay carrots',
      'pepper',
      'red pepper',
      'green pepper',
      'yellow pepper',
    ] },
  { id: 'st-cucumber', name: 'Cucumber, raw', category: 'Vegetables',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 15, protein: 0.7, carbs: 3.6, fat: 0.1, fiber: 0.5, serving_basis: '100g' },
  { id: 'st-lettuce', name: 'Lettuce, raw', category: 'Vegetables',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 15, protein: 1.4, carbs: 2.9, fat: 0.2, fiber: 1.3, serving_basis: '100g' },
  { id: 'st-zucchini', name: 'Zucchini, raw', category: 'Vegetables',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 17, protein: 1.2, carbs: 3.1, fat: 0.3, fiber: 1, serving_basis: '100g',
    aliases: [
      'courgette',
      'cucumber',
      'english cucumber',
      'lebanese cucumber',
      'ridge cucumber',
      'lettuce',
      'iceberg lettuce',
      'romaine lettuce',
      'gem lettuce',
      'little gem',
      'zucchini',
      'yellow zucchini',
      'green zucchini',
    ] },
  { id: 'st-mushroom', name: 'Mushroom, white, raw', category: 'Vegetables',
    regions: ['uk-ie', 'us', 'europe', 'worldwide'],
    kcal: 22, protein: 3.1, carbs: 3.3, fat: 0.3, fiber: 1, serving_basis: '100g' },
  { id: 'st-aubergine', name: 'Aubergine, raw', category: 'Vegetables',
    regions: ['uk-ie', 'europe', 'worldwide'],
    kcal: 25, protein: 1, carbs: 5.9, fat: 0.2, fiber: 3, serving_basis: '100g',
    aliases: [
      'eggplant',
      'mushroom',
      'button mushroom',
      'cremini',
      'chestnut mushroom',
      'portobello',
      'aubergine',
      'baby aubergine',
    ] },
  { id: 'st-tomato-tin', name: 'Tinned tomatoes, chopped', category: 'Vegetables',
    regions: ['uk-ie', 'europe', 'worldwide'],
    kcal: 22, protein: 1.1, carbs: 4, fat: 0.3, fiber: 1, serving_basis: '100g',
    aliases: ['canned tomatoes'] },
  { id: 'st-baked-beans', name: 'Baked beans, in tomato sauce', category: 'Legumes & Beans',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 95, protein: 4.8, carbs: 14, fat: 0.4, fiber: 3.7, serving_basis: '100g' },

  // -------- FRUITS --------
  { id: 'st-banana', name: 'Banana', category: 'Fruits',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 89, protein: 1.1, carbs: 22.8, fat: 0.3, fiber: 2.6, serving_basis: '100g' },
  { id: 'st-apple', name: 'Apple', category: 'Fruits',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 52, protein: 0.3, carbs: 13.8, fat: 0.2, fiber: 2.4, serving_basis: '100g' },
  { id: 'st-orange', name: 'Orange', category: 'Fruits',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 47, protein: 0.9, carbs: 11.8, fat: 0.1, fiber: 2.4, serving_basis: '100g' },
  { id: 'st-blueberries', name: 'Blueberries', category: 'Fruits',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 57, protein: 0.7, carbs: 14.5, fat: 0.3, fiber: 2.4, serving_basis: '100g' },
  { id: 'st-raspberries', name: 'Raspberries', category: 'Fruits',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 52, protein: 1.2, carbs: 11.9, fat: 0.7, fiber: 6.5, serving_basis: '100g' },
  { id: 'st-strawberries', name: 'Strawberries', category: 'Fruits',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 32, protein: 0.7, carbs: 7.7, fat: 0.3, fiber: 2, serving_basis: '100g' },
  { id: 'st-grapes', name: 'Grapes', category: 'Fruits',
    regions: ['uk-ie', 'us', 'europe', 'worldwide'],
    kcal: 67, protein: 0.6, carbs: 17, fat: 0.4, fiber: 0.9, serving_basis: '100g' },
  { id: 'st-mango', name: 'Mango', category: 'Fruits',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 60, protein: 0.8, carbs: 15, fat: 0.4, fiber: 1.6, serving_basis: '100g' },
  { id: 'st-strawberry', name: 'Strawberry', category: 'Fruits',
    regions: ['uk-ie', 'us', 'europe', 'worldwide'],
    kcal: 32, protein: 0.7, carbs: 7.7, fat: 0.3, fiber: 2, serving_basis: '100g' },

  // -------- DAIRY / DRINKS --------
  { id: 'st-milk-whole', name: 'Whole milk', category: 'Milk & Milk Alternatives',
    regions: ['uk-ie', 'us', 'europe', 'worldwide'],
    kcal: 61, protein: 3.2, carbs: 4.8, fat: 3.3, fiber: 0, serving_basis: '100ml' },
  { id: 'st-milk-semi-skimmed', name: 'Semi-skimmed milk', category: 'Milk & Milk Alternatives',
    regions: ['uk-ie', 'europe', 'worldwide'],
    kcal: 46, protein: 3.4, carbs: 4.8, fat: 1.8, fiber: 0, serving_basis: '100ml',
    aliases: [
      'low fat milk',
      '1% milk',
      '2% milk',
      'banana',
      'ripe banana',
      'cavendish banana',
      'plantain',
      'lady finger banana',
      'apple',
      'green apple',
      'red apple',
      'granny smith',
      'braeburn',
      'fuji apple',
      'pink lady apple',
      'orange',
      'navel orange',
      'blood orange',
      'valencia orange',
      'satsuma',
      'clementine',
      'mandarin',
      'blueberry',
      'blueberries',
      'bilberry',
      'raspberry',
      'raspberries',
      'strawberry',
      'strawberries',
      'english strawberries',
      'grape',
      'grapes',
      'red grapes',
      'green grapes',
      'black grapes',
      'seedless grapes',
      'mango',
      'ripe mango',
      'alphonso mango',
      'ataulfo mango',
      'whole milk',
      'full cream milk',
      'full fat milk',
      'semi-skimmed milk',
      'semi skimmed',
      'baked beans',
      'beans',
      'haricot beans',
      'navy beans',
    ] },
  { id: 'st-oat-milk', name: 'Oat milk, unsweetened', category: 'Milk & Milk Alternatives',
    regions: ['uk-ie', 'europe', 'worldwide'],
    kcal: 45, protein: 0.8, carbs: 6.5, fat: 1.5, fiber: 0.8, serving_basis: '100ml' },
  { id: 'st-almond-milk', name: 'Almond milk, unsweetened', category: 'Milk & Milk Alternatives',
    regions: ['uk-ie', 'us', 'europe', 'worldwide'],
    kcal: 13, protein: 0.4, carbs: 0.6, fat: 1.1, fiber: 0.2, serving_basis: '100ml' },

  // -------- PANTRY --------
  { id: 'st-honey', name: 'Honey', category: 'Sweets & Desserts',
    regions: ['uk-ie', 'us', 'europe', 'worldwide'],
    kcal: 304, protein: 0.3, carbs: 82.4, fat: 0, fiber: 0.2, serving_basis: '100g' },
  { id: 'st-peanut-butter-crunchy', name: 'Peanut butter, crunchy', category: 'Nuts & Seeds',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 588, protein: 25, carbs: 20, fat: 50, fiber: 6, serving_basis: '100g' },
  { id: 'st-tomato-puree', name: 'Tomato puree', category: 'Condiments & Sauces',
    regions: ['uk-ie', 'europe', 'worldwide'],
    kcal: 38, protein: 1.6, carbs: 7.2, fat: 0.2, fiber: 1.5, serving_basis: '100g',
    aliases: [
      'tomato paste',
      'oat milk',
      'oatly',
      'oat drink',
      'oat beverage',
      'almond milk',
      'unsweetened almond milk',
      'almond drink',
      'almond beverage',
      'honey',
      'clear honey',
      'set honey',
      'manuka honey',
      'peanut butter',
      'crunchy pb',
      'crunchy',
      'tomato puree',
      'passata',
      'tomato concentrate',
    ] },
  { id: 'st-soya-sauce', name: 'Soy sauce', category: 'Condiments & Sauces',
    regions: ['uk-ie', 'us', 'europe', 'worldwide'],
    kcal: 53, protein: 8.1, carbs: 4.9, fat: 0.6, fiber: 0.8, serving_basis: '100ml',
    aliases: [
      'soy sauce',
      'soya sauce',
      'tamari',
      'light soy sauce',
      'dark soy sauce',
    ] },

  // -------- UK-SPECIFIC --------
  { id: 'st-baked-beans-heinz', name: 'Baked beans (Heinz), in tomato sauce', category: 'Legumes & Beans',
    regions: ['uk-ie', 'worldwide'],
    kcal: 78, protein: 4.7, carbs: 12.5, fat: 0.4, fiber: 3.5, serving_basis: '100g' },
  { id: 'st-tea-bag', name: 'Black tea, brewed', category: 'Beverages',
    regions: ['uk-ie', 'europe', 'worldwide'],
    kcal: 1, protein: 0, carbs: 0.3, fat: 0, fiber: 0, serving_basis: '100ml' },
  { id: 'st-weetabix', name: 'Weetabix, dry', category: 'Breakfast Foods',
    regions: ['uk-ie', 'worldwide'],
    kcal: 362, protein: 12, carbs: 75, fat: 2.5, fiber: 10, serving_basis: '100g',
    aliases: [
      'wheat biscuits',
      'heinz baked beans',
      'heinz beans',
      'beans in tomato sauce',
      'tea',
      'black tea',
      'builders tea',
      'english breakfast tea',
      'earl grey',
      'weetabix',
      'wheat bisks',
      'cereal biscuit',
    ] },
  { id: 'st-marmite', name: 'Marmite, yeast extract', category: 'Condiments & Sauces',
    regions: ['uk-ie', 'worldwide'],
    kcal: 250, protein: 25, carbs: 28, fat: 0.5, fiber: 0, serving_basis: '100g' },
  { id: 'st-yorkshire-tea-cake', name: 'Tea (Yorkshire tea, brewed)', category: 'Beverages',
    regions: ['uk-ie', 'worldwide'],
    kcal: 1, protein: 0, carbs: 0.3, fat: 0, fiber: 0, serving_basis: '100ml',
    aliases: [
      'builders tea',
      'marmite',
      'yeast extract',
      'yeast spread',
      'vegemite (similar)',
      'tea',
      'yorkshire tea',
      'tetley',
      'pg tips',
      'english breakfast',
    ] },
  { id: 'st-hp-sauce', name: 'HP sauce, brown', category: 'Condiments & Sauces',
    regions: ['uk-ie', 'europe', 'worldwide'],
    kcal: 110, protein: 1, carbs: 23, fat: 0, fiber: 0.3, serving_basis: '100g',
    aliases: [
      'brown sauce',
      'hp sauce',
      'hp brown',
      'daddies sauce',
    ] },
  { id: 'st-malted-bread', name: 'Malted bread, sliced', category: 'Bread & Bakery',
    regions: ['uk-ie', 'worldwide'],
    kcal: 260, protein: 9, carbs: 49, fat: 2, fiber: 5, serving_basis: '100g' },

  // -------- US-SPECIFIC --------
  { id: 'st-peanut-butter-jif', name: 'Peanut butter (Jif), creamy', category: 'Nuts & Seeds',
    regions: ['us', 'worldwide'],
    kcal: 588, protein: 22, carbs: 22, fat: 50, fiber: 5, serving_basis: '100g' },
  { id: 'st-ranch-dressing', name: 'Ranch dressing', category: 'Condiments & Sauces',
    regions: ['us', 'worldwide'],
    kcal: 484, protein: 0.8, carbs: 5.5, fat: 51, fiber: 0, serving_basis: '100g' },

  // -------- SNACKS / BREAKFAST --------
  { id: 'st-honey-nut-cheerios', name: 'Honey Nut Cheerios', category: 'Breakfast Foods',
    regions: ['us', 'worldwide'],
    kcal: 379, protein: 8, carbs: 80, fat: 4, fiber: 7, serving_basis: '100g' },
  { id: 'st-banana-bread', name: 'Banana bread', category: 'Snacks',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 326, protein: 5, carbs: 50, fat: 11, fiber: 1.5, serving_basis: '100g' },
  { id: 'st-popcorn-air-popped', name: 'Popcorn, air-popped', category: 'Snacks',
    regions: ['uk-ie', 'us', 'worldwide'],
    kcal: 387, protein: 13, carbs: 78, fat: 4, fiber: 15, serving_basis: '100g' },
  { id: 'st-dark-chocolate-70', name: 'Dark chocolate, 70% cocoa', category: 'Sweets & Desserts',
    regions: ['uk-ie', 'us', 'europe', 'worldwide'],
    kcal: 598, protein: 7.8, carbs: 45.9, fat: 42.6, fiber: 10.9, serving_basis: '100g' },
  { id: 'st-hummus', name: 'Hummus', category: 'Legumes & Beans',
    regions: ['uk-ie', 'europe', 'worldwide'],
    kcal: 166, protein: 8, carbs: 14, fat: 10, fiber: 6, serving_basis: '100g' },
];

// Re-shape for the upsert payload.
const ROWS = STAPLES.map((s) => ({
  id: s.id,
  name: s.name,
  category: s.category,
  regions: s.regions,
  kcal: s.kcal,
  protein: s.protein,
  carbs: s.carbs,
  fat: s.fat,
  fiber: s.fiber,
  serving_basis: s.serving_basis,
  standard_serving_label: s.standard_serving_label ?? null,
  aliases: s.aliases ?? [],
}));

async function main() {
  console.log(`Upserting ${ROWS.length} staple foods into foods_staples...`);

  // POST with Prefer: resolution=merge-duplicates so the PK upserts.
  const BATCH = 100;
  for (let i = 0; i < ROWS.length; i += BATCH) {
    const slice = ROWS.slice(i, i + BATCH);
    const res = await fetch(`${SUPABASE_URL}/rest/v1/foods_staples`, {
      method: 'POST',
      headers: {
        apikey: KEY,
        Authorization: `Bearer ${KEY}`,
        'Content-Type': 'application/json',
        Prefer: 'resolution=merge-duplicates',
      },
      body: JSON.stringify(slice),
    });
    if (!res.ok) {
      const body = await res.text();
      throw new Error(`upsert failed: ${res.status} ${body}`);
    }
    console.log(`  …${Math.min(i + BATCH, ROWS.length)} / ${ROWS.length}`);
  }
  console.log('Done.');
}

main().catch((err) => {
  console.error('Fatal:', err);
  process.exit(1);
});